name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Nome do usuÃ¡rio'
        required: true
      greeting:
        description: 'Mensagem de saudaÃ§Ã£o'
        required: false
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: echo  The tags are ${{ inputs.name }} 
      - name: Print Greeting
        run: |
          if [[ -n "${{ github.event.inputs.greeting }}" ]]; then
            echo "Mensagem de saudaÃ§Ã£o: ${{ inputs.greeting }}"
          else
            echo "Nenhuma mensagem de saudaÃ§Ã£o fornecida. ${{ inpu"
          fi
